import os


SHOPIFY_APP_PRIVATE_APP_PASSWORD = os.getenv('SHOPIFY_APP_PRIVATE_APP_PASSWORD')
SHOPIFY_APP_API_KEY = os.getenv('SHOPIFY_APP_API_KEY')
SHOPIFY_APP_API_SECRET = os.getenv('SHOPIFY_APP_API_SECRET')
SHOPIFY_APP_SHOP_URL = os.getenv('SHOPIFY_APP_SHOP_URL')
#
SHOPIFY_API_VERSION = os.getenv('SHOPIFY_API_VERSION', '2024-07')
#
PS_RESTFUL_API_KEY = os.getenv('PS_RESTFUL_API_KEY')
PS_REST_API = os.getenv('PS_REST_API', 'https://api.psrestful.com/')
