import os


SHOPIFY_APP_PRIVATE_APP_PASSWORD = os.getenv('SHOPIFY_APP_PRIVATE_APP_PASSWORD')
SHOPIFY_APP_API_KEY = os.getenv('SHOPIFY_APP_API_KEY')
SHOPIFY_APP_API_SECRET = os.getenv('SHOPIFY_APP_API_SECRET')
SECRET_KEY = os.getenv('SECRET_KEY')
SHOPIFY_APP_SHOP_URL = os.getenv('SHOPIFY_APP_SHOP_URL')
#
SHOPIFY_API_VERSION = os.getenv('SHOPIFY_API_VERSION', '2024-07')
